server:
  port: 8081
  shutdown: graceful
  forward-headers-strategy: framework
  tomcat:
    redirect-context-root: true

logging:
  level:
    root: INFO
    com.company: INFO

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    try-it-out-enabled: true
    server-url: https://loan-management.up.railway.app
    urls:
      - url: https://loan-management.up.railway.app/v3/api-docs
        name: Production Server

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  lifecycle:
    timeout-per-shutdown-phase: 30s

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${secret}
  expiration: 86400000

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_EMAIL}
  from-name: Optimasys Solutions

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
